### ISSUE TITLE
Transition to SubtleCrypto from Node's crypto module

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/open-payments-node#7]
## Context
Currently, using `@interledger/http-signature-utils` and `@interledger/open-payments` outside of a Node environment is impractical, primarily due to the use on Node's crypto module. The [SubtleCrypto API](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto), while accessible in both browser and Node environments, does not yet offer support for Ed25519 or is experimental:

- In Chromium-based browsers, the algorithm is accessible by activating the `Experimental Web Platform Features` flag 
- In Firefox there is no support the algorithm;
- Safari has support in a stable release;
- In Node, the Ed25519 algorithm is still considered [experimental](https://nodejs.org/dist/latest-v20.x/docs/api/webcrypto.html#ed25519ed448x25519x448-key-pairs);
  
[Ed25519 implementation status](https://github.com/WICG/webcrypto-secure-curves/issues/20)
  
## Todos
- [ ] Transition to SubtleCrypto from Node's crypto module once the Ed25519 curve support becomes stable across all browsers
  - [ ] `@interledger/http-signature-utils`
  - [ ] `@interledger/open-payments`
